DJPR/DJPR/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    path('news/', include('NewsPaper.urls')),
]

DJPR/NewsPaper/urls.py
from django.urls import path
from .views import PostsList, PostDetail, PostSearch, NewsCreate, PostUpdate, PostDelete, CategoryListView, subscribe

urlpatterns = [
   path('', PostsList.as_view()),
   path('<int:pk>/', PostDetail.as_view()),
   path('search/', PostSearch.as_view(), name='search'),
   path('create/', NewsCreate.as_view(), name='news_create'),
   path('articles/create/', NewsCreate.as_view(), name='article_create'),
   path('<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('articles/<int:pk>/edit/', PostUpdate.as_view(), name='post_update'),
   path('<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('articles/<int:pk>/delete/', PostDelete.as_view(), name='post_delete'),
   path('categories/<int:pk>', CategoryListView.as_view(), name='category_list'),
   path('categories/<int:pk>/subscribe', subscribe, name='subscribe'),
]

DJPR/NewsPaper/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Sum
from django.urls import reverse


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    author_rating = models.IntegerField(default=0)

    def update_rating(self):
        author_posts_rating = Post.objects.all().filter(author_id=self.pk).aggregate(
            posts_rating_sum=Sum('rating') * 3)
        author_comments_rating = Comment.objects.all().filter(user_id=self.user).aggregate(
            comments_rating_sum=Sum('rating_com'))

        print(author_posts_rating)
        print(author_comments_rating)

        self.author_rating = author_posts_rating['posts_rating_sum'] + author_comments_rating['comments_rating_sum']
        self.save()


politics = 'PO'
art = 'AR'
show = 'SH'
rest = 'RS'

TOPICS = [
    (politics, 'ПОЛИТИКА'),
    (art, 'ИСКУССТВО'),
    (show, 'Шоу-бизнес'),
    (rest, 'Досуг')
]


class Category(models.Model):
    topic = models.CharField(max_length=2, choices=TOPICS, default=politics, unique=True)
    subscribers = models.ManyToManyField(User, related_name='categories')

    def __str__(self):
        return self.topic.title()


class Post(models.Model):
    ART = 'С'
    NEWS = 'Н'

    TYPES = [(ART, 'Статья'), (NEWS, 'Новость')]
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    post_type = models.CharField(max_length=15, choices=TYPES)
    time_create = models.DateTimeField(auto_now_add=True)
    category = models.ManyToManyField(Category)
    title = models.CharField(max_length=120)
    text = models.TextField()
    rating = models.IntegerField(default=0)

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.text[:125] + '...'

    def __str__(self):
        return f'{self.title.title()}:{self.text.title()}:{self.date_in}'

    def get_absolute_url(self):
        return reverse('post_detail', args=[str(self.id)])


class PostCategory(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=255)
    created_com = models.DateTimeField(auto_now_add=True)
    rating_com = models.IntegerField(default=0)

    def like(self):
        self.rating_com += 1
        self.save()

    def dislike(self):
        self.rating_com -= 1
        self.save()


DJPR/NewsPaper/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Post


class PostForm(forms.ModelForm):
    text = forms.CharField(min_length=20)

    class Meta:
        model = Post
        fields = ['author', 'title', 'text', 'category']

DJPR/NewsPaper/views.py
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, TemplateView
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import redirect, get_object_or_404, render
from django.contrib.auth.decorators import login_required

from .models import Post, Category
from .filter import PostFilter
from .forms import PostForm


class PostsList(ListView):
    model = Post
    ordering = 'time_create'
    template_name = 'news.html'
    context_object_name = 'posts'
    paginate_by = 10


class PostDetail(DetailView):
    model = Post
    template_name = 'new.html'
    context_object_name = 'post'


class PostSearch(ListView):
    model = Post
    ordering = 'time_create'
    template_name = 'search.html'
    context_object_name = 'search'
    paginate_by = 10

    def get_queryset(self):
        queryset = super().get_queryset()
        self.filterset = PostFilter(self.request.GET, queryset=queryset)
        return self.filterset.qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filterset'] = self.filterset
        return context


class NewsCreate(PermissionRequiredMixin, CreateView):
    permission_required = 'news.add_post'
    form_class = PostForm
    model = Post
    template_name = 'news_create.html'

    def form_valid(self, form):
        post = form.save(commit=False)
        if self.request.path == '/news/articles/create/':
            post.article_news = 'AR'
        return super().form_valid(form)


class PostUpdate(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    permission_required = 'news.change_post'
    form_class = PostForm
    model = Post
    template_name = 'post_update.html'


class ProtectedView(LoginRequiredMixin, TemplateView):
    update_name = 'post_update.html'


class PostDelete(DeleteView):
    model = Post
    template_name = 'post_delete.html'
    success_url = reverse_lazy('post_list')


class CategoryListView(ListView):
    model = Post
    template_name = 'category_list.html'
    context_object_name = 'category_news_list'

    def get_queryset(self):
        self.category = get_object_or_404(Category, id=self.kwargs['pk'])
        queryset = Post.objects.filter(category=self.category).order_by('-time_create')
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['is_not_subscriber'] = self.request.user not in self.category.subscribers.all()
        context['category'] = self.category
        return context


@login_required
def subscribe(request, pk):
    user = request.user
    category = Category.objects.get(id=pk)
    category.subscribers.add(user)

    message = 'Вы успешно подписались на рассылку новостей категории'
    return render(request, 'subscribe.html', {'category': category, 'message': message})

DJPR/templates/article_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать статью</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>
{% endblock content %}

DJPR/templates/category_list.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
    <h3> Новости </h3>
    <h4><a href="{{ category.id }}" >{{ category }}</a></h4>
    <form action="" method="get">
        {% csrf_token %}
        {{ filterset.form.as_p }}
        {% if is_not_subscriber %}
         <p class="text-center"><a href="{% url 'subscribe' category.id %}" class="btn btn-secondary btn-sm">Подписаться</a></p>
        {% endif %}
    </form>

    <hr>
    {% if category_news_list %}
        <table>
            <tr>
                <td><b>Заголовок</b></td>
                <td><b>Дата публикации</b></td>
                <td><b>Публикация</b></td>
                <td><b>Тип публикации</b></td>
                <td><b>Категория</b></td>
            </tr>

            {% for post in category_news_list %}
            <tr>
                <td>{{ post.title|truncatechars:20|censor }}</td>
                <td>{{ post.date_in|date:'d M Y' }}</td>
                <td>{{ post.text|truncatechars:50|censor }}</td>
                <td>{{ post.get_article_news_display }}</td>
                <td>{% for category in post.category.all %}
                <a href="{{ category.id }}">{{ category }}</a>
                {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </table>

    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

DJPR/templates/daily_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуйте! Новые статьи за последнюю неделю!</h2>
<ul>
  {% for post in posts %}
      <li><a href="{{ link }}{{ post.get_absolute_url }}">{{ post.title }}</a></li>
  {% endfor %}
</ul>
</body>
</html>

DJPR/templates/new.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Post
{% endblock title %}

{% block content %}
{% if post %}
        <table>
           <tr>
                <td><b>Название</b></td>
                <td><b>Текст</b></td>
                <td><b>Дата загрузки</b></td>
            </tr>
            <tr>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.text|censor }}</td>
                <td>{{ post.time_create|date:'d M Y' }}</td>
            </tr>
        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
{% endblock content %}

DJPR/templates/news.html
{% extends 'flatpages/default.html' %}
{% load custom_filters %}

{% block title %}
Posts
{% endblock title %}

{% block content %}
    <h2>Всего новостей: {{ object_list|length }}</h2>
    {% if posts %}
        <table>
            <tr>
                <td><b>Заголовок</b></td>
                <td><b>Дата публикации</b></td>
                <td><b>Публикация</b></td>
                <td><b>Тип публикации</b></td>
                <td><b>Категория</b></td>

            </tr>

            {% for post in posts %}
            <tr>
                <td>{{ post.title|truncatechars:20|censor }}</td>
                <td>{{ post.time_create|date:'d M Y' }}</td>
                <td>{{ post.text|truncatechars:50|censor }}</td>
                <td>{{ post.get_post_type_display }}</td>
                <td>{% for category in post.category.all %}
                <a href="categories/{{ category.id }}">{{ category }}</a>
                {% endfor %}
                </td>
            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}

   {% if page_obj.has_previous %}
       <a href="?page=1">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?page={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

   {{ page_obj.number }}

   {% if page_obj.has_next %}
       <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?page={{ page_obj.paginator.num_pages }}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

{% endblock content %}

DJPR/templates/news_create.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Создать Новость</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock content %}

DJPR/templates/post_created_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>Здравствуйте! Новая <a href="{{ link }}"> статья </a> в Вашем любимом разделе!</h2>
<p>{{ text }}</p>
</body>
</html>

DJPR/templates/post_delete.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Удаление Новости/Статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.title }}"?</p>
    <input type="submit" value="Delete" />
</form>
{% endblock content %}

DJPR/templates/post_update.html
{% extends 'flatpages/default.html' %}

{% block content %}
<h1>Редактирование Новости/Статьи</h1>
<hr>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save" />
</form>

{% endblock content %}

DJPR/templates/search.html
{% extends 'flatpages/default.html' %}

{% load custom_filters %}

{% load custom_tags %}

{%block title %}
Posts
{% endblock title %}

{% block content %}

    <h1>Найти пост</h1>

    <form action="" method="get">
        {{ filterset.form.as_p }}
        <input type="submit" value="Найти" />
    </form>

    <hr>
    {% if search %}
        <table>
            <tr>
                <td>Название</td>
                <td>Имя автора</td>
                <td>Текст</td>
                <td>Дата</td>
            </tr>

            {% for post in search %}
            <tr>
                <td>{{ post.title|censor }}</td>
                <td>{{ post.author }}</td>
                <td>{{ post.text|truncatechars:50|censor }}</td>
                <td>{{ post.time_create|date:'d M Y' }}</td>

            </tr>
            {% endfor %}
        </table>
    {% else %}
        <h2>Новостей нет!</h2>
    {% endif %}
    {% if page_obj.has_previous %}
        <a href='?{% url_replace page=1 %}'>1</a>
        {% if page_obj.previous_page_number != 1 %}
            ...
            <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
        {%endif %}
    {% endif %}
    {{ page_obj.number }}
    {% if page_obj.has_next %}
        <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
        {% if paginator.num_pages != page_obj.next_page_number %}
            ...
            <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
        {% endif %}
    {% endif %}

{% endblock content %}

DJPR/templates/subscribe.html
{% extends 'flatpages/default.html' %}
{% block content %}
    <h1 class="text-center">{{message}} {{category}}</h1>
{% endblock content %}